import { describe, expect, it } from "vitest";
import {
	adaptColorsForDarkMode,
	adaptForDarkPage,
	hslToRgb,
	mirrorLightness,
	optimizeSVG,
	parseHexColor,
	prefixSvgIds,
	prepareSvgForDisplay,
	relativeLuminance,
	rgbToHsl,
	sanitizeSvg,
	toHex,
} from "../src/svg";

/**
 * Trimmed but structurally faithful dvisvgm 3.6 output: single-quoted
 * attributes, the `xmlns:xlink` declaration without which SVGO refuses to
 * parse, the generated-by comment, and the `<g fill='#000' stroke='#000'>`
 * wrapper that carries the default colour.
 */
const DVISVGM_SVG =
	`<?xml version='1.0' encoding='UTF-8'?>\n` +
	`<!-- This file was generated by dvisvgm 3.6 -->\n` +
	`<svg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='33.46pt' height='8.21pt' viewBox='-43.4 -44.3 33.4 8.2'>\n` +
	`<defs>\n<path id='g0-120' d='M1 2L3 4'/>\n</defs>\n` +
	`<g id='page1' fill='#000' stroke='#000'>\n` +
	`<use x='-43.4' y='-36.2' xlink:href='#g0-120'/>\n` +
	`<path d='M0 0V28.4' fill='#fff' stroke='#000'/>\n` +
	`</g>\n</svg>`;

describe("colour maths", () => {
	it("parses the three- and six-digit forms, with or without the hash", () => {
		expect(parseHexColor("#fff")).toEqual({ r: 255, g: 255, b: 255 });
		expect(parseHexColor("b30000")).toEqual({ r: 179, g: 0, b: 0 });
	});

	it("rejects anything that is not a hex colour", () => {
		expect(parseHexColor("none")).toBeNull();
		expect(parseHexColor("#gg0000")).toBeNull();
		expect(parseHexColor("#12345")).toBeNull();
	});

	it("round-trips rgb through hsl", () => {
		for (const hex of ["#b30000", "#1e90ff", "#808080", "#006400", "#ffffff"]) {
			expect(toHex(hslToRgb(rgbToHsl(parseHexColor(hex)!)))).toBe(hex.toLowerCase());
		}
	});

	it("mirrors lightness while preserving hue and saturation exactly", () => {
		// This is the property the whole dark-mode strategy rests on: if hue
		// drifted, red ink would come back as some other colour.
		for (const hex of ["#b30000", "#00008c", "#006400", "#1e90ff", "#ffffc0"]) {
			const before = rgbToHsl(parseHexColor(hex)!);
			const after = rgbToHsl(mirrorLightness(parseHexColor(hex)!));
			expect(after.h).toBeCloseTo(before.h, 10);
			expect(after.s).toBeCloseTo(before.s, 10);
			expect(after.l).toBeCloseTo(1 - before.l, 10);
		}
	});

	it("leaves mid-tones alone, which are readable on either page", () => {
		expect(toHex(mirrorLightness(parseHexColor("#ff0000")!))).toBe("#ff0000");
		expect(toHex(mirrorLightness(parseHexColor("#00ff00")!))).toBe("#00ff00");
		expect(toHex(mirrorLightness(parseHexColor("#0000ff")!))).toBe("#0000ff");
	});

	it("mirrors the exact values the probe figures produced", () => {
		// Sampled from real compiled output (the colour probe in plan §16.13).
		expect(toHex(mirrorLightness(parseHexColor("#b30000")!))).toBe("#ff4c4c");
		expect(toHex(mirrorLightness(parseHexColor("#f0f0f0")!))).toBe("#0f0f0f");
		expect(toHex(mirrorLightness(parseHexColor("#00008c")!))).toBe("#7373ff");
		expect(toHex(mirrorLightness(parseHexColor("#ffffff")!))).toBe("#000000");
	});
});

describe("adaptForDarkPage", () => {
	const DARK = 0.013;
	const contrast = (a: number, b: number): number =>
		(Math.max(a, b) + 0.05) / (Math.min(a, b) + 0.05);
	const crOnDark = (hex: string): number =>
		contrast(relativeLuminance(adaptForDarkPage(parseHexColor(hex)!)), DARK);
	const crOnLight = (hex: string): number =>
		contrast(relativeLuminance(parseHexColor(hex)!), 1);

	it("keeps every colour that was legible on a light page legible on a dark one", () => {
		// This is the regression that pure mirroring could not pass: HSL
		// lightness is not perceived brightness, so `blue!70` mirrored from
		// 5.55:1 down to 1.31:1 — a legible curve made nearly invisible.
		const legible = ["#b30000", "#4c4cff", "#00008c", "#808080", "#404040", "#006400", "#800080", "#1e90ff"];
		for (const hex of legible) {
			expect(crOnLight(hex)).toBeGreaterThanOrEqual(3);
			expect(crOnDark(hex)).toBeGreaterThanOrEqual(3);
		}
	});

	it("lifts a saturated colour that mirroring would have buried", () => {
		// The concrete case from the showcase: figure 6's epicycloid.
		expect(toHex(adaptForDarkPage(parseHexColor("#4c4cff")!))).toBe("#5d5dbd");
		expect(crOnDark("#4c4cff")).toBeGreaterThanOrEqual(3);
	});

	it("leaves deliberately subtle colours subtle", () => {
		// A near-white box is 1.14:1 against white — a barely-there panel. The
		// floor must not apply to it, or it would become a grey slab.
		expect(toHex(adaptForDarkPage(parseHexColor("#f0f0f0")!))).toBe("#0f0f0f");
		expect(crOnDark("#f0f0f0")).toBeLessThan(1.5);
		expect(toHex(adaptForDarkPage(parseHexColor("#c0c0c0")!))).toBe("#3f3f3f");
		expect(crOnDark("#c0c0c0")).toBeLessThan(2);
	});

	it("preserves hue for every colour it touches", () => {
		for (const hex of ["#b30000", "#4c4cff", "#006400", "#800080", "#1e90ff"]) {
			const before = rgbToHsl(parseHexColor(hex)!);
			const after = rgbToHsl(adaptForDarkPage(parseHexColor(hex)!));
			expect(after.h).toBeCloseTo(before.h, 6);
		}
	});

	it("leaves mid-tone red and green alone, but lifts pure blue", () => {
		// Red and green survive the mirror unchanged and are already fine on a
		// dark page. Pure blue is the interesting one: it is only 1.94:1
		// against #1e1e1e, so it is lifted like any other hard-to-see colour.
		expect(toHex(adaptForDarkPage(parseHexColor("#ff0000")!))).toBe("#ff0000");
		expect(toHex(adaptForDarkPage(parseHexColor("#00ff00")!))).toBe("#00ff00");
		expect(toHex(adaptForDarkPage(parseHexColor("#0000ff")!))).toBe("#4c4cff");
		expect(crOnDark("#0000ff")).toBeGreaterThanOrEqual(3);
	});
});

describe("adaptColorsForDarkMode", () => {
	it("sends pure black to the theme text colour", () => {
		const out = adaptColorsForDarkMode(DVISVGM_SVG);
		expect(out).toContain(`fill='currentColor'`);
		expect(out).toContain(`stroke='currentColor'`);
	});

	it("mirrors white instead of turning it into the page background", () => {
		// The old rule was `white -> var(--background-primary)`. That is right
		// for a background but wrong for white *ink*: white text on a coloured
		// box became the dark page colour and vanished. Mirroring to black
		// keeps it consistent with the box, which mirrors to a light colour.
		const out = adaptColorsForDarkMode(`<path fill='#ffffff'/>`);
		expect(out).toBe(`<path fill='#000000'/>`);
		expect(out).not.toContain("var(--background-primary)");
	});

	it("adapts tints and greys, which the old exact-match rule skipped", () => {
		// Every one of these was invisible or near-invisible in the dark probe.
		const out = adaptColorsForDarkMode(
			`<g fill='#b30000'><path fill='#808080'/><path fill='#f0f0f0'/><path fill='#ffffc0'/></g>`,
		);
		expect(out).toContain(`fill='#ff4c4c'`); // dark red ink -> light red
		expect(out).toContain(`fill='#7f7f7f'`); // mid grey is already fine
		expect(out).toContain(`fill='#0f0f0f'`); // near-white box -> near-black
		expect(out).toContain(`fill='#3f3f00'`); // pale yellow box -> dark olive
	});

	it("handles colours written as style declarations, not just attributes", () => {
		const out = adaptColorsForDarkMode(`<path style='fill:#f0f0f0;stroke:none'/>`);
		expect(out).toBe(`<path style='fill:#0f0f0f;stroke:none'/>`);
	});

	it("handles gradient stops, including dvisvgm's inner whitespace", () => {
		// dvisvgm writes `stop-color=' #000 '` with the spaces *inside* the
		// quotes. A pattern that expects the hex immediately after the quote
		// silently skips every `<stop>`, leaving ball shadings, colormaps and
		// fadings untranslated — which is exactly what happened first time.
		expect(adaptColorsForDarkMode(`<stop stop-color='#ffffc0'/>`)).toBe(
			`<stop stop-color='#3f3f00'/>`,
		);
		expect(adaptColorsForDarkMode(`<stop stop-color=' #f8f8ff '/>`)).toBe(
			`<stop stop-color=' #000007 '/>`,
		);
		expect(adaptColorsForDarkMode(`<stop stop-color=' #000 '/>`)).toBe(
			`<stop stop-color=' currentColor '/>`,
		);
	});

	it("never rewrites an id reference or a non-colour property", () => {
		// `url(#g0-54)` is a font glyph reference; `fill-rule` and
		// `stroke-width` merely start with a colour property name. Rewriting
		// any of them would corrupt the diagram.
		const svg = `<g fill='url(#g0-54)'><path fill-rule='evenodd' stroke-width='0.4'/></g>`;
		expect(adaptColorsForDarkMode(svg)).toBe(svg);
	});

	it("leaves `none` and currentColor alone", () => {
		const svg = `<g fill='none' stroke='currentColor'/>`;
		expect(adaptColorsForDarkMode(svg)).toBe(svg);
	});
});

describe("prefixSvgIds", () => {
	it("namespaces ids and every reference to them", () => {
		const out = prefixSvgIds(DVISVGM_SVG, "tikz-abc12345-");
		expect(out).toContain(`id='tikz-abc12345-g0-120'`);
		expect(out).toContain(`id='tikz-abc12345-page1'`);
		expect(out).toContain(`xlink:href='#tikz-abc12345-g0-120'`);
		expect(out).not.toMatch(/id='g0-120'/);
	});

	it("rewrites url(#id) references", () => {
		const out = prefixSvgIds(`<clipPath id='clip0'/><g clip-path='url(#clip0)'/>`, "p-");
		expect(out).toContain(`id='p-clip0'`);
		expect(out).toContain(`url(#p-clip0)`);
	});

	it("does not partially match an id that is a prefix of another", () => {
		const out = prefixSvgIds(`<a id='g0-1'/><b id='g0-12'/><use href='#g0-12'/>`, "p-");
		expect(out).toContain(`id='p-g0-1'`);
		expect(out).toContain(`id='p-g0-12'`);
		expect(out).toContain(`href='#p-g0-12'`);
	});

	it("is a no-op when there are no ids", () => {
		expect(prefixSvgIds(`<svg><path d='M0 0'/></svg>`, "p-")).toBe(`<svg><path d='M0 0'/></svg>`);
	});
});

describe("sanitizeSvg", () => {
	it("removes script elements", () => {
		expect(sanitizeSvg(`<svg><script>alert(1)</script><path/></svg>`)).not.toContain("script");
	});

	it("removes event handlers", () => {
		const out = sanitizeSvg(`<svg><image onerror="alert(1)" href='x'/></svg>`);
		expect(out).not.toContain("onerror");
	});

	it("removes foreignObject", () => {
		const out = sanitizeSvg(`<svg><foreignObject><div>x</div></foreignObject></svg>`);
		expect(out).not.toContain("foreignObject");
	});

	it("removes the XML declaration and DOCTYPE", () => {
		const out = sanitizeSvg(`<?xml version='1.0'?><!DOCTYPE svg [<!ENTITY x 'y'>]><svg/>`);
		expect(out).not.toContain("<?xml");
		expect(out).not.toContain("DOCTYPE");
	});

	it("removes javascript: URLs", () => {
		expect(sanitizeSvg(`<svg><a href='javascript:alert(1)'/></svg>`)).not.toContain("javascript:");
	});

	it("leaves ordinary diagram markup untouched", () => {
		const out = sanitizeSvg(DVISVGM_SVG);
		expect(out).toContain(`xlink:href='#g0-120'`);
		expect(out).toContain(`viewBox='-43.4 -44.3 33.4 8.2'`);
	});
});

describe("optimizeSVG", () => {
	it("actually runs SVGO on realistic dvisvgm output", () => {
		// preset-default strips comments; if the comment survives, SVGO was
		// bypassed and every other assertion here would be vacuous.
		expect(optimizeSVG(DVISVGM_SVG, "p-")).not.toContain("generated by dvisvgm");
	});

	it("keeps the viewBox so the diagram still scales", () => {
		const out = optimizeSVG(DVISVGM_SVG, "p-");
		expect(out).toContain("viewBox");
	});

	it("keeps ids (cleanupIds disabled) and keeps them prefixed", () => {
		const out = optimizeSVG(DVISVGM_SVG, "p-");
		expect(out).toContain("p-g0-120");
	});

	it("does not throw on the currentColor the dark-mode adaption introduces", () => {
		const adapted = adaptColorsForDarkMode(DVISVGM_SVG);
		expect(() => optimizeSVG(adapted, "p-")).not.toThrow();
		const out = optimizeSVG(adapted, "p-");
		expect(out).toContain("svg");
	});

	it("preserves the adapted colours through a real SVGO pass", () => {
		// If SVGO dropped the adapted colours (by collapsing the wrapper group,
		// say), dark mode would silently break for every diagram.
		const out = optimizeSVG(adaptColorsForDarkMode(DVISVGM_SVG), "p-");
		expect(out).not.toContain("generated by dvisvgm");
		expect(out).toContain("currentColor");
		// The white fill was mirrored to black and survived; note SVGO's
		// convertColors shortens `#000000` to `#000`, so assert on the
		// meaning (a black fill) rather than the literal spelling.
		expect(out).toMatch(/fill="#000"/);
		expect(out).not.toMatch(/#fff/i);
	});

	it("falls back to the raw SVG when given something SVGO cannot parse", () => {
		// Not valid XML: SVGO will complain, and we must still return markup.
		const broken = "<svg><g fill='#000'</svg>";
		expect(() => optimizeSVG(broken, "p-")).not.toThrow();
	});
});

describe("prepareSvgForDisplay", () => {
	it("adapts colours only in adaptive mode AND only on a dark theme", () => {
		expect(prepareSvgForDisplay(DVISVGM_SVG, "p-", "adaptive", true)).toContain("currentColor");
		expect(prepareSvgForDisplay(DVISVGM_SVG, "p-", "adaptive", false)).not.toContain("currentColor");
	});

	it("leaves colours untouched in light-canvas and off modes, dark theme or not", () => {
		// light-canvas gets its readability from the light panel in styles.css,
		// so the colours themselves must stay exactly as TeX drew them.
		for (const mode of ["light-canvas", "off"] as const) {
			const dark = prepareSvgForDisplay(DVISVGM_SVG, "p-", mode, true);
			expect(dark).not.toContain("currentColor");
			expect(dark).toContain("#000");
			expect(dark).toContain("#fff");
		}
	});

	it("defaults to leaving colours alone", () => {
		expect(prepareSvgForDisplay(DVISVGM_SVG, "p-")).not.toContain("currentColor");
	});

	it("always sanitises, even when adaptation is off", () => {
		const hostile = `<svg><script>alert(1)</script><g fill='#000'/></svg>`;
		expect(prepareSvgForDisplay(hostile, "p-", "off", true)).not.toContain("script");
	});
});
