import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

// Both spellings: `fs` and `node:fs` are the same module to Node.
const builtins = [...builtinModules, ...builtinModules.map((name) => `node:${name}`)];

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	// This plugin shells out to a local TeX distribution, so it is a Node
	// (not browser) bundle: `child_process`, `fs`, `os` and `path` are real
	// requires at runtime, not shims. `obsidian` and `electron` are provided
	// by the host app.
	external: [
		"obsidian",
		"electron",
		"@codemirror/*",
		...builtins,
	],
	format: "cjs",
	platform: "node",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	await context.dispose();
} else {
	await context.watch();
}
